### ISSUE TITLE
speakers sound is weak

### ISSUE THREAD

**Issue by medosleem** [PixelExperience-Lavender/xiaomi_lavender_builds#21]

**Comment by medosleem** [comment]
the sound out from speaker is weak although the speaker works well in pe 9 plus

**Comment by nunocodex** [comment]
I listen music and for me is load correctly, what you mean @medosleem ?

**Comment by Ashnetn** [comment]
Overall sound quality and volume is less compared to pie rom

**Comment by nunocodex** [comment]
Already fixed in old official
