### ISSUE TITLE
Headphones dont work in call

### ISSUE THREAD

**Issue by Driverator** [PixelExperience-Lavender/xiaomi_lavender_builds#38]
When i answer the call doesnt matter is it over net or cellular other person cant hear me at all
Opened recorder to test and that fixed it aperantly

**Comment by Driverator** [comment]
Edit : nope its buggy i have to plug it and unplug until it decides to work which killes it for me because i need that for my work while usb headphones work fine

**Comment by Jenping** [comment]
External microphone doesn't work in all apps for me.
