### ISSUE TITLE
FM Radio audio output not working

### ISSUE THREAD

**Issue by arenaslucas** [PixelExperience-Lavender/xiaomi_lavender_builds#40]
FM Radio is not working on build **PixelExperience_lavender-10.0-20191109-1552-OFFICIAL**

**Comment by pepebc** [comment]
PixelExperience_lavender-10.0-20191109-1552-OFFICIAL: FM Radio,
you can record station but you can't hear

**Comment by Driverator** [comment]
Same here

**Comment by nunocodex** [comment]
For a moment I think the issue come from fm radio app, for it i don't build on official.

I don't close this issue for reference.

**Comment by nunocodex** [comment]
Fixed in the current official
