### ISSUE TITLE
Screen lock does not work

### ISSUE THREAD

**Issue by liweichn** [PixelExperience-Lavender/xiaomi_lavender_builds#41]
I can only chose swipe to open my phone, when I set PIN, Pattern or Password，it does not work. Because no password was set, Google smart lock is unavailable, so I can not  know whether the fingerprint is ok.

The rom is **PixelExperience_lavender-10.0-20191109-1552-OFFICIAL.zip**

**Comment by Driverator** [comment]
I put fingerpring strait up when i was setting up phone and there was no problem for me

**Comment by nunocodex** [comment]
> I can only chose swipe to open my phone, when I set PIN, Pattern or Password，it does not work. Because no password was set, Google smart lock is unavailable, so I can not know whether the fingerprint is ok.
> 
> The rom is **PixelExperience_lavender-10.0-20191109-1552-OFFICIAL.zip**

I have this issue too, you need to make new clean flash I think that happen on pe sources after some changes.
