### ISSUE TITLE
Proximity sensor

### ISSUE THREAD

**Issue by SeenYouBefore** [PixelExperience-Lavender/xiaomi_lavender_builds#43]
Global version note 7 - The proximity sensor doesn't work

**Comment by ShehriyarQureshi** [comment]
Can confirm. During call the screen remains lit up.

**Comment by nunocodex** [comment]
Reboot until work or flash anything and try again, is a Xiaomi firmware issue I can't fix it.

**Comment by ShehriyarQureshi** [comment]
@nunocodex I just tried it and it worked now. I'm not sure if it worked after the latest update or something else. But it has been fixed now :+1:

**Comment by SeenYouBefore** [comment]
Well I updated my unit to the 22.11 update and  still not working
(I'm using an app from play store to set proximity sensor setting at every boot), but it's not a good solution.

**Comment by ShehriyarQureshi** [comment]
@SeenYouBefore are you using the 22.11 **0239** version?

**Comment by SeenYouBefore** [comment]
Yes
