### ISSUE TITLE
Auto-rotate feature not working

### ISSUE THREAD

**Issue by Kycko** [PixelExperience-Lavender/xiaomi_lavender_builds#46]
Seems that the auto-rotating is not working on my device 🤔 It's enabled in the main settings, and also I've turned it on for the main screen (launcher). And neither main screen nor YouTube adjust screen orientation when I'm rotating my phone.

**Comment by nunocodex** [comment]
> Seems that the auto-rotating is not working on my device 🤔 It's enabled in the main settings, and also I've turned it on for the main screen (launcher). And neither main screen nor YouTube adjust screen orientation when I'm rotating my phone.

To latest OFFICIAL working because i use it, you tried to clean flash or remove any magisk module?

**Comment by Kycko** [comment]
**nunocodex**, I'm using **PixelExperience_lavender-10.0-20191122-0239-OFFICIAL.zip** too.

I've unblocked my device just tomorrow, installed OrangeFox and made a lot of wipes alongside with formatting _system_ and _data_ partitions before flashing your ROM. Magisk is not installed and **never** had been installed.

**Comment by Kycko** [comment]
Hmm... Problem solved, I've just rebooted my phone and auto-rotate started to work perfectly. Seems that it's not working after first initial startup before first reboot. I think this issue can be closed, thank you for your work.
