### ISSUE TITLE
Always on

### ISSUE THREAD

**Issue by georgerodriguex** [PixelExperience-Lavender/xiaomi_lavender_builds#9]
double tap in always on does not working
and Advanced settings on Lock screen display

**Comment by nunocodex** [comment]
Advanced settings on Lock screen display: not added XiaomiParts so can't open the panel.
double tap in always on does not working: need to testing and log

**Comment by nunocodex** [comment]
Advanced settings show but not working, always on not working without battery charging, with charging working as expected

**Comment by nunocodex** [comment]
I removed from the latest official so I close this issue
